### ISSUE TITLE
Heisenberg Upgrade

### ISSUE THREAD

**Issue by cbarraford** [varnav/binance-node-docker#11]
There is an upcoming [hard fork](https://community.binance.org/topic/2150/binance-chain-testnet-heisenberg-upgrade-announcement) of binance. Will need to upgrade the docker image to `0.6.3` soonish.

**Comment by varnav** [comment]
Currently there is no 0.6.3 prod binary and I can't set different versions for prod binary and test binary. I will bump up version to 0.6.3 when prod binary is out.

**Comment by varnav** [comment]
Ok 0.6.3 prod will not be out soon, I will make 0.6.3 testnet only devel branch then.

**Comment by varnav** [comment]
Please try devel branch.

docker pull varnav/binance-node:devel

**Comment by varnav** [comment]
Latest branch is now 0.6.3
