### ISSUE TITLE
update hub.docker.com image

### ISSUE THREAD

**Issue by cbarraford** [varnav/binance-node-docker#13]
it appears hub.docker.com has an older image from 0.6.2 instead of 0.7. Can you please update it on docker hub?

**Comment by varnav** [comment]
Currently no prod binaries for 0.7.0 are available in the repository, build fails because of this.

**Comment by cbarraford** [comment]
@varnav i was looking to run a testnet binary

**Comment by varnav** [comment]
Unfortunately current image is made to be built for both and will not build if there is no both prod and  testnet binaries available.
