### ISSUE TITLE
Initial seed data

### ISSUE THREAD

**Issue by valentinvieriu** [varnav/binance-node-docker#4]
Thank you for providing this. Actually I've started building the docker image myself too.

Do you have a source for downloading the initial seed? It's quite slow and time consuming to start a node at this moment.

**Comment by varnav** [comment]
Info about seed nodes is already pulled from binance repo, but the data itself... Don't think his exists so far. I will take a look what can be done.

**Comment by valentinvieriu** [comment]
It would be great to have a snapshot. It really takes a long time to download the data. Most of the blockchains offer a way to manually download a starting database

**Comment by aliRamshini72** [comment]
https://docs.binance.org/guides/node/snapshot.html

**Comment by varnav** [comment]
Thank you. I added this info to readme.
