### ISSUE TITLE
Run binance node inside Docker as non root

### ISSUE THREAD

**Issue by valentinvieriu** [varnav/binance-node-docker#5]
At this moment the inside docker we run as root. This has some strange effects when you try to access/delete the volume data and you are not root.
One proposal would be to allow env variables to be set allowing to pass UID and GUID and run as non root user
see https://github.com/nodejs/docker-node/blob/master/12/stretch-slim/Dockerfile#L3

**Comment by varnav** [comment]
Good point. Best practice is not to run anything as root, even inside containers. I will experiment with this in devel branch.

**Comment by varnav** [comment]
Okay that should be done in devel branch now. Use `varnav/binance-node-docker:devel`

**Comment by valentinvieriu** [comment]
Looks good  bout will be great to have an option to pass those as env variables
```
ARG HOST_USER_UID=1000
ARG HOST_USER_GID=1000
```
and then use those env variables
```
RUN groupadd --gid ${HOST_USER_GID} bnbchaind \
  && useradd --uid ${HOST_USER_UID} --gid ${HOST_USER_GID} --shell /bin/bash --no-create-home bnbchaind
```

so by using this you allow the user building the docker to pass in his own UID so that he can have access to the volume data in the case their user has a different UID than 1000

Then you can use [build-arg](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg)
```
docker build --build-arg HOST_USER_UID=9000 --build-arg HOST_USER_GID=1000 .....
```

**Comment by varnav** [comment]
Check this out:

https://github.com/varnav/binance-node-docker/commit/db29b07ac4e5de746b3c5904332be80f9de24ac0

**Comment by varnav** [comment]
All done
